universe            = vanilla
executable          = /afs/cern.ch/user/e/escheull/nobackup/modularized_nurd_hlt_con_ae/condor_train.sh

output              = /afs/cern.ch/user/e/escheull/nobackup/modularized_nurd_hlt_con_ae/condor_logs/train.out
error               = /afs/cern.ch/user/e/escheull/nobackup/modularized_nurd_hlt_con_ae/condor_logs/train.err
log                 = /afs/cern.ch/user/e/escheull/nobackup/modularized_nurd_hlt_con_ae/condor_logs/train.log

request_CPUs        = 4
request_memory      = 48GB
request_GPUs        = 1
+JobFlavour         = "tomorrow"

queue
