method: grid
metric:
  goal: maximize
  name: Val rw_acc
parameters:
  cosine:
    values:
      - 1
  # critic_epochs:
  #   values:
  #     - 2
  epochs:
    values:
      - 30
  exact:
    values:
      - 1
  in_dataset:
    values:
      - jet_features
  joint_indep:
    values:
      - 0
      - 1
  lr:
    values:
      - 0.0001
  manualSeed:
    values:
      - 0
      # - 1
      # - 2
      # - 3
      # - 4
  model_arch:
    values:
      - mlp
  momentum:
    values:
      - 0.9
  optimizer:
    values:
      - adam
  project_name:
    values:
      - jets
  reweight:
    values:
      - 1
  weight_decay:
    values:
      - 0.005
program: main.py
project: nurd-ood-jets